### ISSUE TITLE
[FR]: Look into how JWT's are signed, for security

### ISSUE THREAD

**Issue by GregJohnStewart** [Epic-Breakfast-Productions/OpenQuarterMaster#263]
### Software

Base Station

### Describe what you'd like to see

Currently, we have working certs but needs reviewed for proper security protocol.

When deployed using local installer, currently uses same public/private key as for https: https://github.com/Epic-Breakfast-Productions/OpenQuarterMaster/blob/dev/software/open-qm-base-station/makeInstallers.sh

Is this kosher? Also looking to make sure we are signing properly: https://github.com/Epic-Breakfast-Productions/OpenQuarterMaster/blob/dev/software/open-qm-base-station/src/main/java/tech/ebp/oqm/baseStation/service/JwtService.java

Pull request adding https: https://github.com/Epic-Breakfast-Productions/OpenQuarterMaster/pull/262

### Describe alternatives you've considered

None

### Additional context

None

**Comment by ajoline** [comment]
Internal application communications should be secured using a different key.  The concern here is that some less etiquette deployments might just put this on the internet without concern for security.  Backend coms should always be secured separately.

**Comment by GregJohnStewart** [comment]
@all-contributors please add @ajoline for mentoring, review, and security
